security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: SportOase\Entity\User
                property: username
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - SportOase\Security\IServAuthenticator
            entry_point: SportOase\Security\IServAuthenticator
            logout:
                path: app_logout
                target: iserv_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/oidc/callback, roles: PUBLIC_ACCESS }
        - { path: ^/sportoase/admin, roles: ROLE_ADMIN }
        - { path: ^/sportoase, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_TEACHER, ROLE_USER]
        ROLE_TEACHER: [ROLE_USER]
