services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SportOase\:
        resource: '../../*'
        exclude:
            - '../../Entity/'
            - '../../SportOaseBundle.php'
            - '../../Resources/'
            - '../../DependencyInjection/'

    SportOase\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    SportOase\Service\:
        resource: '../../Service/'
