services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SportOase\:
        resource: '../src/*'
        exclude:
            - '../src/Entity/'
            - '../src/SportOaseBundle.php'

    SportOase\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    SportOase\Service\:
        resource: '../src/Service/'
